name: amm
favicon: null
layout_spectrum: 0.3725132546387613
typography_spectrum: 0.40996722294948995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6431610961444676
  lightness: 0.25077908113598824
  saturation: 0.7078581454697996
  rhythmicContrast: 0.6986952880397439
purpose: []
